import * as fs from 'fs';

let code = fs.readFileSync('src/pages/DrLilyPage.tsx', 'utf8');

const startIndex = code.indexOf('{step === "result" && reportData && (');
if (startIndex === -1) throw new Error("Could not find start index");

// Find proper end bracket
let bracketLevels = 0;
let endIndex = -1;
let started = false;

for (let i = startIndex; i < code.length; i++) {
  if (code[i] === '{' || code[i] === '(') {
    bracketLevels++;
    started = true;
  } else if (code[i] === '}' || code[i] === ')') {
    bracketLevels--;
  }
  
  if (started && bracketLevels === 0) {
    endIndex = i;
    break;
  }
}

if (endIndex === -1) throw new Error("Could not find end index");

const replacement = `{step === "result" && reportData && (
              <motion.div
                key="result"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="w-full min-h-screen text-white pb-24 flex flex-col items-center"
              >
                {/* AI Disclaimer Banner */}
                <div className="bg-[#1C1C22]/80 backdrop-blur-md border-b border-[#2A2A35] py-3 px-6 sticky top-0 z-50 text-center w-full shadow-md">
                  <p className="text-[10px] md:text-xs font-bold leading-relaxed max-w-4xl mx-auto text-[#A0A0B0]">
                    ⚠️ This assessment was generated by Dr. Lily, an AI
                    assistant trained exclusively on veterinary science. It is
                    not a substitute for professional veterinary diagnosis or
                    treatment. Please consult a licensed veterinarian.
                  </p>
                </div>

                <div className="w-full flex justify-center py-12 px-2 sm:px-6 overflow-x-auto">
                  <div
                    id="lily-report-content"
                    className="w-full max-w-[794px] bg-white text-zinc-900 shadow-2xl p-8 sm:p-12 mb-8 relative"
                    style={{ minHeight: '1123px' }}
                  >
                    {/* Header */}
                    <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center border-b-2 border-zinc-900 pb-6 mb-8 gap-4">
                      <div>
                        <h1 className="font-serif font-black text-3xl mb-1 text-emerald-800">SenVetCare</h1>
                        <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-500">Dr. Tamal B. Sen Memorial Veterinary Clinic</p>
                      </div>
                      <div className="text-left sm:text-right text-xs text-zinc-600 font-medium">
                        <p>123 Clinic Address, Kolkata</p>
                        <p>Phone: 9871155162</p>
                        <p>contact@senvetcare.com</p>
                      </div>
                    </div>

                    <div className="text-center mb-10">
                      <h2 className="font-bold text-xl uppercase tracking-widest border-2 border-zinc-900 inline-block px-6 py-2 mb-3">Clinical Discharge Summary</h2>
                      <p className="text-xs font-bold text-zinc-500 uppercase tracking-widest">AI-Generated Provisional Assessment</p>
                      <p className="text-[10px] text-zinc-400 font-mono mt-1">Ref ID: {reportData.consultationId || \`LILY-\${Date.now()}\`}</p>
                    </div>

                    {/* Patient Details */}
                    <div className="border border-zinc-300 p-6 mb-10 bg-zinc-50/50">
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 text-sm">
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Owner Name</p>
                          <p className="font-bold text-zinc-800">{formData.ownerName}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Date</p>
                          <p className="font-bold text-zinc-800">{new Date().toLocaleDateString()}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Patient Name</p>
                          <p className="font-bold text-zinc-800">{formData.petName}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Species / Breed</p>
                          <p className="font-bold text-zinc-800">{formData.species} {formData.breed ? \`(\${formData.breed})\` : ''}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Age / Sex</p>
                          <p className="font-bold text-zinc-800">{formData.age} {formData.ageUnit} • {formData.sex}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Weight</p>
                          <p className="font-bold text-zinc-800">{formData.weight} kg</p>
                        </div>
                         <div>
                          <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">Urgency Level</p>
                          <p className={\`font-bold \${reportData.urgencyLevel === "RED" ? 'text-red-600' : reportData.urgencyLevel === "ORANGE" ? 'text-orange-500' : 'text-emerald-600'}\`}>{reportData.urgencyLevel}</p>
                        </div>
                      </div>
                    </div>

                    {/* Summary */}
                    <div className="mb-10">
                      <h3 className="text-xs font-black uppercase tracking-widest text-zinc-800 border-b border-zinc-200 pb-2 mb-4">Summary of Symptoms</h3>
                      <p className="text-sm leading-relaxed text-zinc-700 italic border-l-4 border-emerald-500 pl-4 py-1">"{reportData.summary}"</p>
                    </div>

                    {/* Differential Diagnoses */}
                    {reportData.differentialDiagnoses?.length > 0 && (
                      <div className="mb-10">
                        <h3 className="text-xs font-black uppercase tracking-widest text-zinc-800 border-b border-zinc-200 pb-2 mb-4">Provisional Assessment (Differentials)</h3>
                        <div className="space-y-4">
                          {reportData.differentialDiagnoses.map((d: any, i: number) => (
                            <div key={i} className="bg-white border border-zinc-200 p-4 shadow-sm">
                              <div className="flex justify-between items-start mb-2">
                                <h4 className="font-bold text-zinc-800">{d.condition}</h4>
                                <span className="font-mono text-xs font-bold bg-zinc-100 text-zinc-600 px-2 py-1 rounded">
                                  {typeof d.probability === "number" ? d.probability + "%" : d.probability}
                                </span>
                              </div>
                              <p className="text-xs text-zinc-600 leading-relaxed">{d.reasoning}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Diagnostics & Treatment */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
                      <div>
                         <h3 className="text-xs font-black uppercase tracking-widest text-zinc-800 border-b border-zinc-200 pb-2 mb-4">Recommended Diagnostics</h3>
                         <ul className="list-disc pl-4 text-xs text-zinc-700 space-y-2">
                            {reportData.recommendedTests?.map((t: string, i: number) => (
                              <li key={i}>{t}</li>
                            ))}
                            {reportData.clinicDiagnosticServices?.map((s: any, i: number) => (
                               <li key={\`c-\${i}\`}>{s.service} {s.inHouse ? '(Available In-House)' : ''}</li>
                            ))}
                         </ul>
                      </div>
                      <div>
                         <h3 className="text-xs font-black uppercase tracking-widest text-zinc-800 border-b border-zinc-200 pb-2 mb-4">Line of Treatment & Home Care</h3>
                         <p className="text-xs text-zinc-700 leading-relaxed mb-3">{reportData.generalTreatment}</p>
                         <ul className="list-disc pl-4 text-xs text-zinc-700 space-y-2">
                            {(reportData.homeManagementAdvice || reportData.homeManagement)?.map((t: string, i: number) => (
                              <li key={i}>{t}</li>
                            ))}
                         </ul>
                      </div>
                    </div>

                     {/* Warnings */}
                     {reportData.warningSigns?.length > 0 && (
                        <div className="mb-10 p-5 bg-red-50 border border-red-100 rounded-lg">
                          <h3 className="text-[10px] font-black uppercase tracking-widest text-red-600 mb-3 flex items-center gap-2">
                            <span className="material-symbols-outlined text-sm">warning</span> Escalate Immediately If:
                          </h3>
                          <ul className="list-disc pl-4 text-xs text-red-800 space-y-1">
                            {reportData.warningSigns.map((t: string, i: number) => (
                                <li key={i}>{t}</li>
                            ))}
                          </ul>
                        </div>
                     )}

                     <div className="mt-16 pt-8 border-t border-zinc-200 flex justify-between items-end">
                       <div className="text-[10px] text-zinc-400">
                          <p>Electronically generated report by AI.</p>
                          <p>Not valid without physical examination by a registered practitioner.</p>
                       </div>
                       <div className="text-right">
                          <div className="inline-block border-b border-zinc-800 w-32 mb-2"></div>
                          <p className="text-xs font-bold text-zinc-800">Veterinarian / Assessor</p>
                       </div>
                     </div>
                  </div>
                </div>

                {/* Actions outside report */}
                <div className="w-full max-w-3xl mx-auto px-6 mb-16 relative z-10">
                  
                  <h3 className="font-manrope font-black text-center text-xl mb-8 text-[#A0A0B0] uppercase tracking-widest">Choose Your Next Step</h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                     <a href="/book" className="bg-[#6EE7B7] text-[#0D0D0F] p-6 rounded-[2rem] flex flex-col items-center justify-center text-center hover:bg-[#4ADBA0] transition-colors shadow-lg group">
                        <span className="material-symbols-outlined text-3xl mb-3 group-hover:scale-110 transition-transform">event_available</span>
                        <span className="font-bold uppercase tracking-widest text-xs">Book Consultation</span>
                     </a>
                     <a href="https://wa.me/919871155162" target="_blank" rel="noreferrer" className="bg-[#25D366] text-white p-6 rounded-[2rem] flex flex-col items-center justify-center text-center hover:bg-[#1EBE5D] transition-colors shadow-lg group">
                        <svg className="w-8 h-8 mb-3 fill-current group-hover:scale-110 transition-transform" viewBox="0 0 24 24"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51a12.8 12.8 0 0 0-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z"/></svg>
                        <span className="font-bold uppercase tracking-widest text-xs">WhatsApp Us</span>
                     </a>
                     <a href="tel:9871155162" className="bg-[#1C1C22] text-[#F2F2F4] border border-[#2A2A35] p-6 rounded-[2rem] flex flex-col items-center justify-center text-center hover:border-[#606070] transition-colors shadow-lg group">
                        <span className="material-symbols-outlined text-3xl mb-3 group-hover:scale-110 transition-transform">call</span>
                        <span className="font-bold uppercase tracking-widest text-xs">Call Clinic</span>
                     </a>
                  </div>

                  <div className="mt-8 flex justify-center">
                     <button
                        onClick={() => {
                          const element = document.getElementById("lily-report-content");
                          if (!element) return;
                          Promise.all([import("html-to-image"), import("jspdf")])
                            .then(([htmlToImage, jsPDFModule]) => {
                              htmlToImage.toPng(element, { backgroundColor: "#ffffff", pixelRatio: 2 })
                                .then((dataUrl) => {
                                  const jsPDF = jsPDFModule.jsPDF || jsPDFModule.default?.jsPDF;
                                  if (!jsPDF) {
                                    alert("jsPDF export not available.");
                                    return;
                                  }
                                  const pdf = new jsPDF("p", "mm", "a4");
                                  const pdfWidth = pdf.internal.pageSize.getWidth();
                                  const pdfHeight = (element.offsetHeight * pdfWidth) / element.offsetWidth;
                                  pdf.addImage(dataUrl, "PNG", 0, 0, pdfWidth, pdfHeight);
                                  pdf.save(\`Discharge-Summary-\${formData.petName || 'Patient'}-\${new Date().getTime()}.pdf\`);
                                })
                                .catch(err => {
                                  console.error("PDF generation error:", err);
                                  alert("Error generating PDF.");
                                });
                            })
                            .catch(err => alert("Error loading PDF generator."));
                        }}
                        className="bg-[#141418] border border-[#2A2A35] text-[#A0A0B0] px-8 py-4 rounded-full font-bold uppercase tracking-widest text-[10px] hover:text-white hover:border-[#606070] transition-colors flex items-center gap-2"
                     >
                        <span className="material-symbols-outlined text-lg">download</span>
                        Download PDF Report
                     </button>
                  </div>
                </div>
              </motion.div>
            )}`;

console.log("Replacing block starting at", startIndex, "and ending at", endIndex);
code = code.substring(0, startIndex) + replacement + code.substring(endIndex + 1);

fs.writeFileSync('src/pages/DrLilyPage.tsx', code);
